version: '3'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./create-db.sql:/docker-entrypoint-initdb.d/create_database.sql

  telegram_app:
    container_name: telegram_ai_agent
    build:
      context: .
      dockerfile: Dockerfile
    command: python src/main.py
    restart: always
    env_file:
      - variables.env