version: '3'

services:
  telegram_app:
    container_name: telegram_ai_agent
    build:
      context: .
      dockerfile: Dockerfile
    command: python src/main.py
    restart: always
    env_file:
      - variables.env